# Use a imagem base do PostgreSQL
FROM postgres:15

ENV POSTGRES_USER=G5
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=chatbot

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432
# Usa a imagem oficial do PostgreSQL como base, na versão 15
FROM postgres:15

# Define variáveis de ambiente para configurar o banco de dados
ENV POSTGRES_USER=G5
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=chatbot

# Expõe a porta padrão usada pelo PostgreSQL para comunicação, que é 5432
EXPOSE 5432
